// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/account-screen/AccountScreen.tsx": () => import("../components/mockups/account-screen/AccountScreen.tsx"),
  "./components/mockups/auth-login/AuthLogin.tsx": () => import("../components/mockups/auth-login/AuthLogin.tsx"),
  "./components/mockups/auth-login/AuthSignup.tsx": () => import("../components/mockups/auth-login/AuthSignup.tsx"),
  "./components/mockups/chat-screen/ChatScreen.tsx": () => import("../components/mockups/chat-screen/ChatScreen.tsx"),
  "./components/mockups/full-app-preview/FullAppPreview.tsx": () => import("../components/mockups/full-app-preview/FullAppPreview.tsx"),
  "./components/mockups/loading-screen/LoadingScreen.tsx": () => import("../components/mockups/loading-screen/LoadingScreen.tsx"),
  "./components/mockups/notifications-screen/NotificationsScreen.tsx": () => import("../components/mockups/notifications-screen/NotificationsScreen.tsx"),
  "./components/mockups/paywall-screen/PaywallScreen.tsx": () => import("../components/mockups/paywall-screen/PaywallScreen.tsx"),
  "./components/mockups/picks-screen/PicksScreen.tsx": () => import("../components/mockups/picks-screen/PicksScreen.tsx"),
  "./components/mockups/scan-redesign/ScanRedesign.tsx": () => import("../components/mockups/scan-redesign/ScanRedesign.tsx"),
  "./components/mockups/scan-idle/ScanIdle.tsx": () => import("../components/mockups/scan-idle/ScanIdle.tsx"),
  "./components/mockups/scan-result/ScanResult.tsx": () => import("../components/mockups/scan-result/ScanResult.tsx"),
  "./components/mockups/sport-selector/SportSelector.tsx": () => import("../components/mockups/sport-selector/SportSelector.tsx"),
  "./components/mockups/terms-screen/TermsScreen.tsx": () => import("../components/mockups/terms-screen/TermsScreen.tsx")
};
