// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/loading-screen/LoadingScreen.tsx": () => import("../components/mockups/loading-screen/LoadingScreen.tsx"),
  "./components/mockups/full-app-preview/FullAppPreview.tsx": () => import("../components/mockups/full-app-preview/FullAppPreview.tsx"),
  "./components/mockups/sport-selector/SportSelector.tsx": () => import("../components/mockups/sport-selector/SportSelector.tsx"),
  "./components/mockups/scan-redesign/ScanRedesign.tsx": () => import("../components/mockups/scan-redesign/ScanRedesign.tsx")
};
